---
development:
  cloud_name: diamond-eye-digital
  api_key: '639746954873482'
  api_secret: KsPtMPCOBt1FodbSLFSwsngiXGw
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: diamond-eye-digital
  api_key: '639746954873482'
  api_secret: KsPtMPCOBt1FodbSLFSwsngiXGw
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: diamond-eye-digital
  api_key: '639746954873482'
  api_secret: KsPtMPCOBt1FodbSLFSwsngiXGw
  enhance_image_tag: true
  static_image_support: false
